# Generated by Django 5.0.1 on 2025-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
