# Generated by Django 5.0.1 on 2025-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_stock_name_stock_company_name_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
